### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by paulober** [paulober/FBI#1]
@Steveice10 Hi, I just wanted to ask if you are okay with me continuing to maintain your awesome project FBI. 

If yes, what would you like the author of the ROM to be called? 
Would you be okay with me maintaining this project under the `MPL-2.0` license?
And what do you think of this copyright file-header:
```c
/*
 * Copyright (c) 2015-2019 Steveice10
 * All rights reserved.
 *
 * This source code is licensed under the MIT License found in the
 * LICENSE-MIT file in the root directory of this source tree.
 *
 * Copyright (c) 2023 paulober
 * All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
```

**Comment by paulober** [comment]
@Steveice10, does this mean it's OK?

**Comment by Steveice10** [comment]
It's MIT licensed, you can do what you want as long as you respect that license.

**Comment by paulober** [comment]
Ok, thanks. Didn't mean to bug you.
